package com.jme3.system.jopenvr;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.ptr.IntByReference;
import java.nio.IntBuffer;
/**
 * JNA Wrapper for library <b>JOpenVR</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class JOpenVRLibrary implements Library {
	public static final String JNA_LIBRARY_NAME = "openvr_api";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(JOpenVRLibrary.JNA_LIBRARY_NAME);
	static {
		Native.register(JOpenVRLibrary.class, JOpenVRLibrary.JNA_NATIVE_LIB);
	}
	/** enum values */
	public static interface EVREye {
		public static final int EVREye_Eye_Left = 0;
		public static final int EVREye_Eye_Right = 1;
	};
	/** enum values */
	public static interface EGraphicsAPIConvention {
		public static final int EGraphicsAPIConvention_API_DirectX = 0;
		public static final int EGraphicsAPIConvention_API_OpenGL = 1;
	};
	/** enum values */
	public static interface EColorSpace {
		public static final int EColorSpace_ColorSpace_Auto = 0;
		public static final int EColorSpace_ColorSpace_Gamma = 1;
		public static final int EColorSpace_ColorSpace_Linear = 2;
	};
	/** enum values */
	public static interface ETrackingResult {
		public static final int ETrackingResult_TrackingResult_Uninitialized = 1;
		public static final int ETrackingResult_TrackingResult_Calibrating_InProgress = 100;
		public static final int ETrackingResult_TrackingResult_Calibrating_OutOfRange = 101;
		public static final int ETrackingResult_TrackingResult_Running_OK = 200;
		public static final int ETrackingResult_TrackingResult_Running_OutOfRange = 201;
	};
	/** enum values */
	public static interface ETrackedDeviceClass {
		public static final int ETrackedDeviceClass_TrackedDeviceClass_Invalid = 0;
		public static final int ETrackedDeviceClass_TrackedDeviceClass_HMD = 1;
		public static final int ETrackedDeviceClass_TrackedDeviceClass_Controller = 2;
		public static final int ETrackedDeviceClass_TrackedDeviceClass_TrackingReference = 4;
		public static final int ETrackedDeviceClass_TrackedDeviceClass_Other = 1000;
	};
	/** enum values */
	public static interface ETrackedControllerRole {
		public static final int ETrackedControllerRole_TrackedControllerRole_Invalid = 0;
		public static final int ETrackedControllerRole_TrackedControllerRole_LeftHand = 1;
		public static final int ETrackedControllerRole_TrackedControllerRole_RightHand = 2;
	};
	/** enum values */
	public static interface ETrackingUniverseOrigin {
		public static final int ETrackingUniverseOrigin_TrackingUniverseSeated = 0;
		public static final int ETrackingUniverseOrigin_TrackingUniverseStanding = 1;
		public static final int ETrackingUniverseOrigin_TrackingUniverseRawAndUncalibrated = 2;
	};
	/** enum values */
	public static interface ETrackedDeviceProperty {
		public static final int ETrackedDeviceProperty_Prop_TrackingSystemName_String = 1000;
		public static final int ETrackedDeviceProperty_Prop_ModelNumber_String = 1001;
		public static final int ETrackedDeviceProperty_Prop_SerialNumber_String = 1002;
		public static final int ETrackedDeviceProperty_Prop_RenderModelName_String = 1003;
		public static final int ETrackedDeviceProperty_Prop_WillDriftInYaw_Bool = 1004;
		public static final int ETrackedDeviceProperty_Prop_ManufacturerName_String = 1005;
		public static final int ETrackedDeviceProperty_Prop_TrackingFirmwareVersion_String = 1006;
		public static final int ETrackedDeviceProperty_Prop_HardwareRevision_String = 1007;
		public static final int ETrackedDeviceProperty_Prop_AllWirelessDongleDescriptions_String = 1008;
		public static final int ETrackedDeviceProperty_Prop_ConnectedWirelessDongle_String = 1009;
		public static final int ETrackedDeviceProperty_Prop_DeviceIsWireless_Bool = 1010;
		public static final int ETrackedDeviceProperty_Prop_DeviceIsCharging_Bool = 1011;
		public static final int ETrackedDeviceProperty_Prop_DeviceBatteryPercentage_Float = 1012;
		public static final int ETrackedDeviceProperty_Prop_StatusDisplayTransform_Matrix34 = 1013;
		public static final int ETrackedDeviceProperty_Prop_Firmware_UpdateAvailable_Bool = 1014;
		public static final int ETrackedDeviceProperty_Prop_Firmware_ManualUpdate_Bool = 1015;
		public static final int ETrackedDeviceProperty_Prop_Firmware_ManualUpdateURL_String = 1016;
		public static final int ETrackedDeviceProperty_Prop_HardwareRevision_Uint64 = 1017;
		public static final int ETrackedDeviceProperty_Prop_FirmwareVersion_Uint64 = 1018;
		public static final int ETrackedDeviceProperty_Prop_FPGAVersion_Uint64 = 1019;
		public static final int ETrackedDeviceProperty_Prop_VRCVersion_Uint64 = 1020;
		public static final int ETrackedDeviceProperty_Prop_RadioVersion_Uint64 = 1021;
		public static final int ETrackedDeviceProperty_Prop_DongleVersion_Uint64 = 1022;
		public static final int ETrackedDeviceProperty_Prop_BlockServerShutdown_Bool = 1023;
		public static final int ETrackedDeviceProperty_Prop_CanUnifyCoordinateSystemWithHmd_Bool = 1024;
		public static final int ETrackedDeviceProperty_Prop_ContainsProximitySensor_Bool = 1025;
		public static final int ETrackedDeviceProperty_Prop_DeviceProvidesBatteryStatus_Bool = 1026;
		public static final int ETrackedDeviceProperty_Prop_DeviceCanPowerOff_Bool = 1027;
		public static final int ETrackedDeviceProperty_Prop_Firmware_ProgrammingTarget_String = 1028;
		public static final int ETrackedDeviceProperty_Prop_DeviceClass_Int32 = 1029;
		public static final int ETrackedDeviceProperty_Prop_HasCamera_Bool = 1030;
		public static final int ETrackedDeviceProperty_Prop_DriverVersion_String = 1031;
		public static final int ETrackedDeviceProperty_Prop_Firmware_ForceUpdateRequired_Bool = 1032;
		public static final int ETrackedDeviceProperty_Prop_ReportsTimeSinceVSync_Bool = 2000;
		public static final int ETrackedDeviceProperty_Prop_SecondsFromVsyncToPhotons_Float = 2001;
		public static final int ETrackedDeviceProperty_Prop_DisplayFrequency_Float = 2002;
		public static final int ETrackedDeviceProperty_Prop_UserIpdMeters_Float = 2003;
		public static final int ETrackedDeviceProperty_Prop_CurrentUniverseId_Uint64 = 2004;
		public static final int ETrackedDeviceProperty_Prop_PreviousUniverseId_Uint64 = 2005;
		public static final int ETrackedDeviceProperty_Prop_DisplayFirmwareVersion_Uint64 = 2006;
		public static final int ETrackedDeviceProperty_Prop_IsOnDesktop_Bool = 2007;
		public static final int ETrackedDeviceProperty_Prop_DisplayMCType_Int32 = 2008;
		public static final int ETrackedDeviceProperty_Prop_DisplayMCOffset_Float = 2009;
		public static final int ETrackedDeviceProperty_Prop_DisplayMCScale_Float = 2010;
		public static final int ETrackedDeviceProperty_Prop_EdidVendorID_Int32 = 2011;
		public static final int ETrackedDeviceProperty_Prop_DisplayMCImageLeft_String = 2012;
		public static final int ETrackedDeviceProperty_Prop_DisplayMCImageRight_String = 2013;
		public static final int ETrackedDeviceProperty_Prop_DisplayGCBlackClamp_Float = 2014;
		public static final int ETrackedDeviceProperty_Prop_EdidProductID_Int32 = 2015;
		public static final int ETrackedDeviceProperty_Prop_CameraToHeadTransform_Matrix34 = 2016;
		public static final int ETrackedDeviceProperty_Prop_DisplayGCType_Int32 = 2017;
		public static final int ETrackedDeviceProperty_Prop_DisplayGCOffset_Float = 2018;
		public static final int ETrackedDeviceProperty_Prop_DisplayGCScale_Float = 2019;
		public static final int ETrackedDeviceProperty_Prop_DisplayGCPrescale_Float = 2020;
		public static final int ETrackedDeviceProperty_Prop_DisplayGCImage_String = 2021;
		public static final int ETrackedDeviceProperty_Prop_LensCenterLeftU_Float = 2022;
		public static final int ETrackedDeviceProperty_Prop_LensCenterLeftV_Float = 2023;
		public static final int ETrackedDeviceProperty_Prop_LensCenterRightU_Float = 2024;
		public static final int ETrackedDeviceProperty_Prop_LensCenterRightV_Float = 2025;
		public static final int ETrackedDeviceProperty_Prop_UserHeadToEyeDepthMeters_Float = 2026;
		public static final int ETrackedDeviceProperty_Prop_CameraFirmwareVersion_Uint64 = 2027;
		public static final int ETrackedDeviceProperty_Prop_CameraFirmwareDescription_String = 2028;
		public static final int ETrackedDeviceProperty_Prop_DisplayFPGAVersion_Uint64 = 2029;
		public static final int ETrackedDeviceProperty_Prop_DisplayBootloaderVersion_Uint64 = 2030;
		public static final int ETrackedDeviceProperty_Prop_DisplayHardwareVersion_Uint64 = 2031;
		public static final int ETrackedDeviceProperty_Prop_AudioFirmwareVersion_Uint64 = 2032;
		public static final int ETrackedDeviceProperty_Prop_CameraCompatibilityMode_Int32 = 2033;
		public static final int ETrackedDeviceProperty_Prop_ScreenshotHorizontalFieldOfViewDegrees_Float = 2034;
		public static final int ETrackedDeviceProperty_Prop_ScreenshotVerticalFieldOfViewDegrees_Float = 2035;
		public static final int ETrackedDeviceProperty_Prop_DisplaySuppressed_Bool = 2036;
		public static final int ETrackedDeviceProperty_Prop_AttachedDeviceId_String = 3000;
		public static final int ETrackedDeviceProperty_Prop_SupportedButtons_Uint64 = 3001;
		public static final int ETrackedDeviceProperty_Prop_Axis0Type_Int32 = 3002;
		public static final int ETrackedDeviceProperty_Prop_Axis1Type_Int32 = 3003;
		public static final int ETrackedDeviceProperty_Prop_Axis2Type_Int32 = 3004;
		public static final int ETrackedDeviceProperty_Prop_Axis3Type_Int32 = 3005;
		public static final int ETrackedDeviceProperty_Prop_Axis4Type_Int32 = 3006;
		public static final int ETrackedDeviceProperty_Prop_ControllerRoleHint_Int32 = 3007;
		public static final int ETrackedDeviceProperty_Prop_FieldOfViewLeftDegrees_Float = 4000;
		public static final int ETrackedDeviceProperty_Prop_FieldOfViewRightDegrees_Float = 4001;
		public static final int ETrackedDeviceProperty_Prop_FieldOfViewTopDegrees_Float = 4002;
		public static final int ETrackedDeviceProperty_Prop_FieldOfViewBottomDegrees_Float = 4003;
		public static final int ETrackedDeviceProperty_Prop_TrackingRangeMinimumMeters_Float = 4004;
		public static final int ETrackedDeviceProperty_Prop_TrackingRangeMaximumMeters_Float = 4005;
		public static final int ETrackedDeviceProperty_Prop_ModeLabel_String = 4006;
		public static final int ETrackedDeviceProperty_Prop_VendorSpecific_Reserved_Start = 10000;
		public static final int ETrackedDeviceProperty_Prop_VendorSpecific_Reserved_End = 10999;
	};
	/** enum values */
	public static interface ETrackedPropertyError {
		public static final int ETrackedPropertyError_TrackedProp_Success = 0;
		public static final int ETrackedPropertyError_TrackedProp_WrongDataType = 1;
		public static final int ETrackedPropertyError_TrackedProp_WrongDeviceClass = 2;
		public static final int ETrackedPropertyError_TrackedProp_BufferTooSmall = 3;
		public static final int ETrackedPropertyError_TrackedProp_UnknownProperty = 4;
		public static final int ETrackedPropertyError_TrackedProp_InvalidDevice = 5;
		public static final int ETrackedPropertyError_TrackedProp_CouldNotContactServer = 6;
		public static final int ETrackedPropertyError_TrackedProp_ValueNotProvidedByDevice = 7;
		public static final int ETrackedPropertyError_TrackedProp_StringExceedsMaximumLength = 8;
		public static final int ETrackedPropertyError_TrackedProp_NotYetAvailable = 9;
	};
	/** enum values */
	public static interface EVRSubmitFlags {
		public static final int EVRSubmitFlags_Submit_Default = 0;
		public static final int EVRSubmitFlags_Submit_LensDistortionAlreadyApplied = 1;
		public static final int EVRSubmitFlags_Submit_GlRenderBuffer = 2;
	};
	/** enum values */
	public static interface EVRState {
		public static final int EVRState_VRState_Undefined = -1;
		public static final int EVRState_VRState_Off = 0;
		public static final int EVRState_VRState_Searching = 1;
		public static final int EVRState_VRState_Searching_Alert = 2;
		public static final int EVRState_VRState_Ready = 3;
		public static final int EVRState_VRState_Ready_Alert = 4;
		public static final int EVRState_VRState_NotReady = 5;
		public static final int EVRState_VRState_Standby = 6;
		public static final int EVRState_VRState_Ready_Alert_Low = 7;
	};
	/** enum values */
	public static interface EVREventType {
		public static final int EVREventType_VREvent_None = 0;
		public static final int EVREventType_VREvent_TrackedDeviceActivated = 100;
		public static final int EVREventType_VREvent_TrackedDeviceDeactivated = 101;
		public static final int EVREventType_VREvent_TrackedDeviceUpdated = 102;
		public static final int EVREventType_VREvent_TrackedDeviceUserInteractionStarted = 103;
		public static final int EVREventType_VREvent_TrackedDeviceUserInteractionEnded = 104;
		public static final int EVREventType_VREvent_IpdChanged = 105;
		public static final int EVREventType_VREvent_EnterStandbyMode = 106;
		public static final int EVREventType_VREvent_LeaveStandbyMode = 107;
		public static final int EVREventType_VREvent_TrackedDeviceRoleChanged = 108;
		public static final int EVREventType_VREvent_WatchdogWakeUpRequested = 109;
		public static final int EVREventType_VREvent_ButtonPress = 200;
		public static final int EVREventType_VREvent_ButtonUnpress = 201;
		public static final int EVREventType_VREvent_ButtonTouch = 202;
		public static final int EVREventType_VREvent_ButtonUntouch = 203;
		public static final int EVREventType_VREvent_MouseMove = 300;
		public static final int EVREventType_VREvent_MouseButtonDown = 301;
		public static final int EVREventType_VREvent_MouseButtonUp = 302;
		public static final int EVREventType_VREvent_FocusEnter = 303;
		public static final int EVREventType_VREvent_FocusLeave = 304;
		public static final int EVREventType_VREvent_Scroll = 305;
		public static final int EVREventType_VREvent_TouchPadMove = 306;
		public static final int EVREventType_VREvent_OverlayFocusChanged = 307;
		public static final int EVREventType_VREvent_InputFocusCaptured = 400;
		public static final int EVREventType_VREvent_InputFocusReleased = 401;
		public static final int EVREventType_VREvent_SceneFocusLost = 402;
		public static final int EVREventType_VREvent_SceneFocusGained = 403;
		public static final int EVREventType_VREvent_SceneApplicationChanged = 404;
		public static final int EVREventType_VREvent_SceneFocusChanged = 405;
		public static final int EVREventType_VREvent_InputFocusChanged = 406;
		public static final int EVREventType_VREvent_SceneApplicationSecondaryRenderingStarted = 407;
		public static final int EVREventType_VREvent_HideRenderModels = 410;
		public static final int EVREventType_VREvent_ShowRenderModels = 411;
		public static final int EVREventType_VREvent_OverlayShown = 500;
		public static final int EVREventType_VREvent_OverlayHidden = 501;
		public static final int EVREventType_VREvent_DashboardActivated = 502;
		public static final int EVREventType_VREvent_DashboardDeactivated = 503;
		public static final int EVREventType_VREvent_DashboardThumbSelected = 504;
		public static final int EVREventType_VREvent_DashboardRequested = 505;
		public static final int EVREventType_VREvent_ResetDashboard = 506;
		public static final int EVREventType_VREvent_RenderToast = 507;
		public static final int EVREventType_VREvent_ImageLoaded = 508;
		public static final int EVREventType_VREvent_ShowKeyboard = 509;
		public static final int EVREventType_VREvent_HideKeyboard = 510;
		public static final int EVREventType_VREvent_OverlayGamepadFocusGained = 511;
		public static final int EVREventType_VREvent_OverlayGamepadFocusLost = 512;
		public static final int EVREventType_VREvent_OverlaySharedTextureChanged = 513;
		public static final int EVREventType_VREvent_DashboardGuideButtonDown = 514;
		public static final int EVREventType_VREvent_DashboardGuideButtonUp = 515;
		public static final int EVREventType_VREvent_ScreenshotTriggered = 516;
		public static final int EVREventType_VREvent_ImageFailed = 517;
		public static final int EVREventType_VREvent_RequestScreenshot = 520;
		public static final int EVREventType_VREvent_ScreenshotTaken = 521;
		public static final int EVREventType_VREvent_ScreenshotFailed = 522;
		public static final int EVREventType_VREvent_SubmitScreenshotToDashboard = 523;
		public static final int EVREventType_VREvent_ScreenshotProgressToDashboard = 524;
		public static final int EVREventType_VREvent_Notification_Shown = 600;
		public static final int EVREventType_VREvent_Notification_Hidden = 601;
		public static final int EVREventType_VREvent_Notification_BeginInteraction = 602;
		public static final int EVREventType_VREvent_Notification_Destroyed = 603;
		public static final int EVREventType_VREvent_Quit = 700;
		public static final int EVREventType_VREvent_ProcessQuit = 701;
		public static final int EVREventType_VREvent_QuitAborted_UserPrompt = 702;
		public static final int EVREventType_VREvent_QuitAcknowledged = 703;
		public static final int EVREventType_VREvent_DriverRequestedQuit = 704;
		public static final int EVREventType_VREvent_ChaperoneDataHasChanged = 800;
		public static final int EVREventType_VREvent_ChaperoneUniverseHasChanged = 801;
		public static final int EVREventType_VREvent_ChaperoneTempDataHasChanged = 802;
		public static final int EVREventType_VREvent_ChaperoneSettingsHaveChanged = 803;
		public static final int EVREventType_VREvent_SeatedZeroPoseReset = 804;
		public static final int EVREventType_VREvent_AudioSettingsHaveChanged = 820;
		public static final int EVREventType_VREvent_BackgroundSettingHasChanged = 850;
		public static final int EVREventType_VREvent_CameraSettingsHaveChanged = 851;
		public static final int EVREventType_VREvent_ReprojectionSettingHasChanged = 852;
		public static final int EVREventType_VREvent_ModelSkinSettingsHaveChanged = 853;
		public static final int EVREventType_VREvent_EnvironmentSettingsHaveChanged = 854;
		public static final int EVREventType_VREvent_StatusUpdate = 900;
		public static final int EVREventType_VREvent_MCImageUpdated = 1000;
		public static final int EVREventType_VREvent_FirmwareUpdateStarted = 1100;
		public static final int EVREventType_VREvent_FirmwareUpdateFinished = 1101;
		public static final int EVREventType_VREvent_KeyboardClosed = 1200;
		public static final int EVREventType_VREvent_KeyboardCharInput = 1201;
		public static final int EVREventType_VREvent_KeyboardDone = 1202;
		public static final int EVREventType_VREvent_ApplicationTransitionStarted = 1300;
		public static final int EVREventType_VREvent_ApplicationTransitionAborted = 1301;
		public static final int EVREventType_VREvent_ApplicationTransitionNewAppStarted = 1302;
		public static final int EVREventType_VREvent_ApplicationListUpdated = 1303;
		public static final int EVREventType_VREvent_ApplicationMimeTypeLoad = 1304;
		public static final int EVREventType_VREvent_Compositor_MirrorWindowShown = 1400;
		public static final int EVREventType_VREvent_Compositor_MirrorWindowHidden = 1401;
		public static final int EVREventType_VREvent_Compositor_ChaperoneBoundsShown = 1410;
		public static final int EVREventType_VREvent_Compositor_ChaperoneBoundsHidden = 1411;
		public static final int EVREventType_VREvent_TrackedCamera_StartVideoStream = 1500;
		public static final int EVREventType_VREvent_TrackedCamera_StopVideoStream = 1501;
		public static final int EVREventType_VREvent_TrackedCamera_PauseVideoStream = 1502;
		public static final int EVREventType_VREvent_TrackedCamera_ResumeVideoStream = 1503;
		public static final int EVREventType_VREvent_PerformanceTest_EnableCapture = 1600;
		public static final int EVREventType_VREvent_PerformanceTest_DisableCapture = 1601;
		public static final int EVREventType_VREvent_PerformanceTest_FidelityLevel = 1602;
		public static final int EVREventType_VREvent_VendorSpecific_Reserved_Start = 10000;
		public static final int EVREventType_VREvent_VendorSpecific_Reserved_End = 19999;
	};
	/** enum values */
	public static interface EDeviceActivityLevel {
		public static final int EDeviceActivityLevel_k_EDeviceActivityLevel_Unknown = -1;
		public static final int EDeviceActivityLevel_k_EDeviceActivityLevel_Idle = 0;
		public static final int EDeviceActivityLevel_k_EDeviceActivityLevel_UserInteraction = 1;
		public static final int EDeviceActivityLevel_k_EDeviceActivityLevel_UserInteraction_Timeout = 2;
		public static final int EDeviceActivityLevel_k_EDeviceActivityLevel_Standby = 3;
	};
	/** enum values */
	public static interface EVRButtonId {
		public static final int EVRButtonId_k_EButton_System = 0;
		public static final int EVRButtonId_k_EButton_ApplicationMenu = 1;
		public static final int EVRButtonId_k_EButton_Grip = 2;
		public static final int EVRButtonId_k_EButton_DPad_Left = 3;
		public static final int EVRButtonId_k_EButton_DPad_Up = 4;
		public static final int EVRButtonId_k_EButton_DPad_Right = 5;
		public static final int EVRButtonId_k_EButton_DPad_Down = 6;
		public static final int EVRButtonId_k_EButton_A = 7;
		public static final int EVRButtonId_k_EButton_Axis0 = 32;
		public static final int EVRButtonId_k_EButton_Axis1 = 33;
		public static final int EVRButtonId_k_EButton_Axis2 = 34;
		public static final int EVRButtonId_k_EButton_Axis3 = 35;
		public static final int EVRButtonId_k_EButton_Axis4 = 36;
		public static final int EVRButtonId_k_EButton_SteamVR_Touchpad = 32;
		public static final int EVRButtonId_k_EButton_SteamVR_Trigger = 33;
		public static final int EVRButtonId_k_EButton_Dashboard_Back = 2;
		public static final int EVRButtonId_k_EButton_Max = 64;
	};
	/** enum values */
	public static interface EVRMouseButton {
		public static final int EVRMouseButton_VRMouseButton_Left = 1;
		public static final int EVRMouseButton_VRMouseButton_Right = 2;
		public static final int EVRMouseButton_VRMouseButton_Middle = 4;
	};
	/** enum values */
	public static interface EVRControllerAxisType {
		public static final int EVRControllerAxisType_k_eControllerAxis_None = 0;
		public static final int EVRControllerAxisType_k_eControllerAxis_TrackPad = 1;
		public static final int EVRControllerAxisType_k_eControllerAxis_Joystick = 2;
		public static final int EVRControllerAxisType_k_eControllerAxis_Trigger = 3;
	};
	/** enum values */
	public static interface EVRControllerEventOutputType {
		public static final int EVRControllerEventOutputType_ControllerEventOutput_OSEvents = 0;
		public static final int EVRControllerEventOutputType_ControllerEventOutput_VREvents = 1;
	};
	/** enum values */
	public static interface ECollisionBoundsStyle {
		public static final int ECollisionBoundsStyle_COLLISION_BOUNDS_STYLE_BEGINNER = 0;
		public static final int ECollisionBoundsStyle_COLLISION_BOUNDS_STYLE_INTERMEDIATE = 1;
		public static final int ECollisionBoundsStyle_COLLISION_BOUNDS_STYLE_SQUARES = 2;
		public static final int ECollisionBoundsStyle_COLLISION_BOUNDS_STYLE_ADVANCED = 3;
		public static final int ECollisionBoundsStyle_COLLISION_BOUNDS_STYLE_NONE = 4;
		public static final int ECollisionBoundsStyle_COLLISION_BOUNDS_STYLE_COUNT = 5;
	};
	/** enum values */
	public static interface EVROverlayError {
		public static final int EVROverlayError_VROverlayError_None = 0;
		public static final int EVROverlayError_VROverlayError_UnknownOverlay = 10;
		public static final int EVROverlayError_VROverlayError_InvalidHandle = 11;
		public static final int EVROverlayError_VROverlayError_PermissionDenied = 12;
		public static final int EVROverlayError_VROverlayError_OverlayLimitExceeded = 13;
		public static final int EVROverlayError_VROverlayError_WrongVisibilityType = 14;
		public static final int EVROverlayError_VROverlayError_KeyTooLong = 15;
		public static final int EVROverlayError_VROverlayError_NameTooLong = 16;
		public static final int EVROverlayError_VROverlayError_KeyInUse = 17;
		public static final int EVROverlayError_VROverlayError_WrongTransformType = 18;
		public static final int EVROverlayError_VROverlayError_InvalidTrackedDevice = 19;
		public static final int EVROverlayError_VROverlayError_InvalidParameter = 20;
		public static final int EVROverlayError_VROverlayError_ThumbnailCantBeDestroyed = 21;
		public static final int EVROverlayError_VROverlayError_ArrayTooSmall = 22;
		public static final int EVROverlayError_VROverlayError_RequestFailed = 23;
		public static final int EVROverlayError_VROverlayError_InvalidTexture = 24;
		public static final int EVROverlayError_VROverlayError_UnableToLoadFile = 25;
		public static final int EVROverlayError_VROVerlayError_KeyboardAlreadyInUse = 26;
		public static final int EVROverlayError_VROverlayError_NoNeighbor = 27;
	};
	/** enum values */
	public static interface EVRApplicationType {
		public static final int EVRApplicationType_VRApplication_Other = 0;
		public static final int EVRApplicationType_VRApplication_Scene = 1;
		public static final int EVRApplicationType_VRApplication_Overlay = 2;
		public static final int EVRApplicationType_VRApplication_Background = 3;
		public static final int EVRApplicationType_VRApplication_Utility = 4;
		public static final int EVRApplicationType_VRApplication_VRMonitor = 5;
		public static final int EVRApplicationType_VRApplication_SteamWatchdog = 6;
		public static final int EVRApplicationType_VRApplication_Max = 7;
	};
	/** enum values */
	public static interface EVRFirmwareError {
		public static final int EVRFirmwareError_VRFirmwareError_None = 0;
		public static final int EVRFirmwareError_VRFirmwareError_Success = 1;
		public static final int EVRFirmwareError_VRFirmwareError_Fail = 2;
	};
	/** enum values */
	public static interface EVRNotificationError {
		public static final int EVRNotificationError_VRNotificationError_OK = 0;
		public static final int EVRNotificationError_VRNotificationError_InvalidNotificationId = 100;
		public static final int EVRNotificationError_VRNotificationError_NotificationQueueFull = 101;
		public static final int EVRNotificationError_VRNotificationError_InvalidOverlayHandle = 102;
		public static final int EVRNotificationError_VRNotificationError_SystemWithUserValueAlreadyExists = 103;
	};
	/** enum values */
	public static interface EVRInitError {
		public static final int EVRInitError_VRInitError_None = 0;
		public static final int EVRInitError_VRInitError_Unknown = 1;
		public static final int EVRInitError_VRInitError_Init_InstallationNotFound = 100;
		public static final int EVRInitError_VRInitError_Init_InstallationCorrupt = 101;
		public static final int EVRInitError_VRInitError_Init_VRClientDLLNotFound = 102;
		public static final int EVRInitError_VRInitError_Init_FileNotFound = 103;
		public static final int EVRInitError_VRInitError_Init_FactoryNotFound = 104;
		public static final int EVRInitError_VRInitError_Init_InterfaceNotFound = 105;
		public static final int EVRInitError_VRInitError_Init_InvalidInterface = 106;
		public static final int EVRInitError_VRInitError_Init_UserConfigDirectoryInvalid = 107;
		public static final int EVRInitError_VRInitError_Init_HmdNotFound = 108;
		public static final int EVRInitError_VRInitError_Init_NotInitialized = 109;
		public static final int EVRInitError_VRInitError_Init_PathRegistryNotFound = 110;
		public static final int EVRInitError_VRInitError_Init_NoConfigPath = 111;
		public static final int EVRInitError_VRInitError_Init_NoLogPath = 112;
		public static final int EVRInitError_VRInitError_Init_PathRegistryNotWritable = 113;
		public static final int EVRInitError_VRInitError_Init_AppInfoInitFailed = 114;
		public static final int EVRInitError_VRInitError_Init_Retry = 115;
		public static final int EVRInitError_VRInitError_Init_InitCanceledByUser = 116;
		public static final int EVRInitError_VRInitError_Init_AnotherAppLaunching = 117;
		public static final int EVRInitError_VRInitError_Init_SettingsInitFailed = 118;
		public static final int EVRInitError_VRInitError_Init_ShuttingDown = 119;
		public static final int EVRInitError_VRInitError_Init_TooManyObjects = 120;
		public static final int EVRInitError_VRInitError_Init_NoServerForBackgroundApp = 121;
		public static final int EVRInitError_VRInitError_Init_NotSupportedWithCompositor = 122;
		public static final int EVRInitError_VRInitError_Init_NotAvailableToUtilityApps = 123;
		public static final int EVRInitError_VRInitError_Init_Internal = 124;
		public static final int EVRInitError_VRInitError_Init_HmdDriverIdIsNone = 125;
		public static final int EVRInitError_VRInitError_Init_HmdNotFoundPresenceFailed = 126;
		public static final int EVRInitError_VRInitError_Init_VRMonitorNotFound = 127;
		public static final int EVRInitError_VRInitError_Init_VRMonitorStartupFailed = 128;
		public static final int EVRInitError_VRInitError_Init_LowPowerWatchdogNotSupported = 129;
		public static final int EVRInitError_VRInitError_Init_InvalidApplicationType = 130;
		public static final int EVRInitError_VRInitError_Init_NotAvailableToWatchdogApps = 131;
		public static final int EVRInitError_VRInitError_Init_WatchdogDisabledInSettings = 132;
		public static final int EVRInitError_VRInitError_Driver_Failed = 200;
		public static final int EVRInitError_VRInitError_Driver_Unknown = 201;
		public static final int EVRInitError_VRInitError_Driver_HmdUnknown = 202;
		public static final int EVRInitError_VRInitError_Driver_NotLoaded = 203;
		public static final int EVRInitError_VRInitError_Driver_RuntimeOutOfDate = 204;
		public static final int EVRInitError_VRInitError_Driver_HmdInUse = 205;
		public static final int EVRInitError_VRInitError_Driver_NotCalibrated = 206;
		public static final int EVRInitError_VRInitError_Driver_CalibrationInvalid = 207;
		public static final int EVRInitError_VRInitError_Driver_HmdDisplayNotFound = 208;
		public static final int EVRInitError_VRInitError_Driver_TrackedDeviceInterfaceUnknown = 209;
		public static final int EVRInitError_VRInitError_Driver_HmdDriverIdOutOfBounds = 211;
		public static final int EVRInitError_VRInitError_Driver_HmdDisplayMirrored = 212;
		public static final int EVRInitError_VRInitError_IPC_ServerInitFailed = 300;
		public static final int EVRInitError_VRInitError_IPC_ConnectFailed = 301;
		public static final int EVRInitError_VRInitError_IPC_SharedStateInitFailed = 302;
		public static final int EVRInitError_VRInitError_IPC_CompositorInitFailed = 303;
		public static final int EVRInitError_VRInitError_IPC_MutexInitFailed = 304;
		public static final int EVRInitError_VRInitError_IPC_Failed = 305;
		public static final int EVRInitError_VRInitError_IPC_CompositorConnectFailed = 306;
		public static final int EVRInitError_VRInitError_IPC_CompositorInvalidConnectResponse = 307;
		public static final int EVRInitError_VRInitError_IPC_ConnectFailedAfterMultipleAttempts = 308;
		public static final int EVRInitError_VRInitError_Compositor_Failed = 400;
		public static final int EVRInitError_VRInitError_Compositor_D3D11HardwareRequired = 401;
		public static final int EVRInitError_VRInitError_Compositor_FirmwareRequiresUpdate = 402;
		public static final int EVRInitError_VRInitError_Compositor_OverlayInitFailed = 403;
		public static final int EVRInitError_VRInitError_Compositor_ScreenshotsInitFailed = 404;
		public static final int EVRInitError_VRInitError_VendorSpecific_UnableToConnectToOculusRuntime = 1000;
		public static final int EVRInitError_VRInitError_VendorSpecific_HmdFound_CantOpenDevice = 1101;
		public static final int EVRInitError_VRInitError_VendorSpecific_HmdFound_UnableToRequestConfigStart = 1102;
		public static final int EVRInitError_VRInitError_VendorSpecific_HmdFound_NoStoredConfig = 1103;
		public static final int EVRInitError_VRInitError_VendorSpecific_HmdFound_ConfigTooBig = 1104;
		public static final int EVRInitError_VRInitError_VendorSpecific_HmdFound_ConfigTooSmall = 1105;
		public static final int EVRInitError_VRInitError_VendorSpecific_HmdFound_UnableToInitZLib = 1106;
		public static final int EVRInitError_VRInitError_VendorSpecific_HmdFound_CantReadFirmwareVersion = 1107;
		public static final int EVRInitError_VRInitError_VendorSpecific_HmdFound_UnableToSendUserDataStart = 1108;
		public static final int EVRInitError_VRInitError_VendorSpecific_HmdFound_UnableToGetUserDataStart = 1109;
		public static final int EVRInitError_VRInitError_VendorSpecific_HmdFound_UnableToGetUserDataNext = 1110;
		public static final int EVRInitError_VRInitError_VendorSpecific_HmdFound_UserDataAddressRange = 1111;
		public static final int EVRInitError_VRInitError_VendorSpecific_HmdFound_UserDataError = 1112;
		public static final int EVRInitError_VRInitError_VendorSpecific_HmdFound_ConfigFailedSanityCheck = 1113;
		public static final int EVRInitError_VRInitError_Steam_SteamInstallationNotFound = 2000;
	};
	/** enum values */
	public static interface EVRScreenshotType {
		public static final int EVRScreenshotType_VRScreenshotType_None = 0;
		public static final int EVRScreenshotType_VRScreenshotType_Mono = 1;
		public static final int EVRScreenshotType_VRScreenshotType_Stereo = 2;
		public static final int EVRScreenshotType_VRScreenshotType_Cubemap = 3;
		public static final int EVRScreenshotType_VRScreenshotType_MonoPanorama = 4;
		public static final int EVRScreenshotType_VRScreenshotType_StereoPanorama = 5;
	};
	/** enum values */
	public static interface EVRScreenshotPropertyFilenames {
		public static final int EVRScreenshotPropertyFilenames_VRScreenshotPropertyFilenames_Preview = 0;
		public static final int EVRScreenshotPropertyFilenames_VRScreenshotPropertyFilenames_VR = 1;
	};
	/** enum values */
	public static interface EVRTrackedCameraError {
		public static final int EVRTrackedCameraError_VRTrackedCameraError_None = 0;
		public static final int EVRTrackedCameraError_VRTrackedCameraError_OperationFailed = 100;
		public static final int EVRTrackedCameraError_VRTrackedCameraError_InvalidHandle = 101;
		public static final int EVRTrackedCameraError_VRTrackedCameraError_InvalidFrameHeaderVersion = 102;
		public static final int EVRTrackedCameraError_VRTrackedCameraError_OutOfHandles = 103;
		public static final int EVRTrackedCameraError_VRTrackedCameraError_IPCFailure = 104;
		public static final int EVRTrackedCameraError_VRTrackedCameraError_NotSupportedForThisDevice = 105;
		public static final int EVRTrackedCameraError_VRTrackedCameraError_SharedMemoryFailure = 106;
		public static final int EVRTrackedCameraError_VRTrackedCameraError_FrameBufferingFailure = 107;
		public static final int EVRTrackedCameraError_VRTrackedCameraError_StreamSetupFailure = 108;
		public static final int EVRTrackedCameraError_VRTrackedCameraError_InvalidGLTextureId = 109;
		public static final int EVRTrackedCameraError_VRTrackedCameraError_InvalidSharedTextureHandle = 110;
		public static final int EVRTrackedCameraError_VRTrackedCameraError_FailedToGetGLTextureId = 111;
		public static final int EVRTrackedCameraError_VRTrackedCameraError_SharedTextureFailure = 112;
		public static final int EVRTrackedCameraError_VRTrackedCameraError_NoFrameAvailable = 113;
		public static final int EVRTrackedCameraError_VRTrackedCameraError_InvalidArgument = 114;
		public static final int EVRTrackedCameraError_VRTrackedCameraError_InvalidFrameBufferSize = 115;
	};
	/** enum values */
	public static interface EVRTrackedCameraFrameType {
		public static final int EVRTrackedCameraFrameType_VRTrackedCameraFrameType_Distorted = 0;
		public static final int EVRTrackedCameraFrameType_VRTrackedCameraFrameType_Undistorted = 1;
		public static final int EVRTrackedCameraFrameType_VRTrackedCameraFrameType_MaximumUndistorted = 2;
		public static final int EVRTrackedCameraFrameType_MAX_CAMERA_FRAME_TYPES = 3;
	};
	public static interface EVRApplicationError {
		public static final int EVRApplicationError_VRApplicationError_None = 0;
		public static final int EVRApplicationError_VRApplicationError_AppKeyAlreadyExists = 100;
		public static final int EVRApplicationError_VRApplicationError_NoManifest = 101;
		public static final int EVRApplicationError_VRApplicationError_NoApplication = 102;
		public static final int EVRApplicationError_VRApplicationError_InvalidIndex = 103;
		public static final int EVRApplicationError_VRApplicationError_UnknownApplication = 104;
		public static final int EVRApplicationError_VRApplicationError_IPCFailed = 105;
		public static final int EVRApplicationError_VRApplicationError_ApplicationAlreadyRunning = 106;
		public static final int EVRApplicationError_VRApplicationError_InvalidManifest = 107;
		public static final int EVRApplicationError_VRApplicationError_InvalidApplication = 108;
		public static final int EVRApplicationError_VRApplicationError_LaunchFailed = 109;
		public static final int EVRApplicationError_VRApplicationError_ApplicationAlreadyStarting = 110;
		public static final int EVRApplicationError_VRApplicationError_LaunchInProgress = 111;
		public static final int EVRApplicationError_VRApplicationError_OldApplicationQuitting = 112;
		public static final int EVRApplicationError_VRApplicationError_TransitionAborted = 113;
		public static final int EVRApplicationError_VRApplicationError_IsTemplate = 114;
		public static final int EVRApplicationError_VRApplicationError_BufferTooSmall = 200;
		public static final int EVRApplicationError_VRApplicationError_PropertyNotSet = 201;
		public static final int EVRApplicationError_VRApplicationError_UnknownProperty = 202;
		public static final int EVRApplicationError_VRApplicationError_InvalidParameter = 203;
	};
	/** enum values */
	public static interface EVRApplicationProperty {
		public static final int EVRApplicationProperty_VRApplicationProperty_Name_String = 0;
		public static final int EVRApplicationProperty_VRApplicationProperty_LaunchType_String = 11;
		public static final int EVRApplicationProperty_VRApplicationProperty_WorkingDirectory_String = 12;
		public static final int EVRApplicationProperty_VRApplicationProperty_BinaryPath_String = 13;
		public static final int EVRApplicationProperty_VRApplicationProperty_Arguments_String = 14;
		public static final int EVRApplicationProperty_VRApplicationProperty_URL_String = 15;
		public static final int EVRApplicationProperty_VRApplicationProperty_Description_String = 50;
		public static final int EVRApplicationProperty_VRApplicationProperty_NewsURL_String = 51;
		public static final int EVRApplicationProperty_VRApplicationProperty_ImagePath_String = 52;
		public static final int EVRApplicationProperty_VRApplicationProperty_Source_String = 53;
		public static final int EVRApplicationProperty_VRApplicationProperty_IsDashboardOverlay_Bool = 60;
		public static final int EVRApplicationProperty_VRApplicationProperty_IsTemplate_Bool = 61;
		public static final int EVRApplicationProperty_VRApplicationProperty_IsInstanced_Bool = 62;
		public static final int EVRApplicationProperty_VRApplicationProperty_LastLaunchTime_Uint64 = 70;
	};
	/** enum values */
	public static interface EVRApplicationTransitionState {
		public static final int EVRApplicationTransitionState_VRApplicationTransition_None = 0;
		public static final int EVRApplicationTransitionState_VRApplicationTransition_OldAppQuitSent = 10;
		public static final int EVRApplicationTransitionState_VRApplicationTransition_WaitingForExternalLaunch = 11;
		public static final int EVRApplicationTransitionState_VRApplicationTransition_NewAppLaunched = 20;
	};
	/** enum values */
	public static interface ChaperoneCalibrationState {
		public static final int ChaperoneCalibrationState_OK = 1;
		public static final int ChaperoneCalibrationState_Warning = 100;
		public static final int ChaperoneCalibrationState_Warning_BaseStationMayHaveMoved = 101;
		public static final int ChaperoneCalibrationState_Warning_BaseStationRemoved = 102;
		public static final int ChaperoneCalibrationState_Warning_SeatedBoundsInvalid = 103;
		public static final int ChaperoneCalibrationState_Error = 200;
		public static final int ChaperoneCalibrationState_Error_BaseStationUninitalized = 201;
		public static final int ChaperoneCalibrationState_Error_BaseStationConflict = 202;
		public static final int ChaperoneCalibrationState_Error_PlayAreaInvalid = 203;
		public static final int ChaperoneCalibrationState_Error_CollisionBoundsInvalid = 204;
	};
	/** enum values */
	public static interface EChaperoneConfigFile {
		public static final int EChaperoneConfigFile_Live = 1;
		public static final int EChaperoneConfigFile_Temp = 2;
	};
	/** enum values */
	public static interface EChaperoneImportFlags {
		public static final int EChaperoneImportFlags_EChaperoneImport_BoundsOnly = 1;
	};
	public static interface EVRCompositorError {
		public static final int EVRCompositorError_VRCompositorError_None = 0;
		public static final int EVRCompositorError_VRCompositorError_RequestFailed = 1;
		public static final int EVRCompositorError_VRCompositorError_IncompatibleVersion = 100;
		public static final int EVRCompositorError_VRCompositorError_DoNotHaveFocus = 101;
		public static final int EVRCompositorError_VRCompositorError_InvalidTexture = 102;
		public static final int EVRCompositorError_VRCompositorError_IsNotSceneApplication = 103;
		public static final int EVRCompositorError_VRCompositorError_TextureIsOnWrongDevice = 104;
		public static final int EVRCompositorError_VRCompositorError_TextureUsesUnsupportedFormat = 105;
		public static final int EVRCompositorError_VRCompositorError_SharedTexturesNotSupported = 106;
		public static final int EVRCompositorError_VRCompositorError_IndexOutOfRange = 107;
	};
	/** enum values */
	public static interface VROverlayInputMethod {
		public static final int VROverlayInputMethod_None = 0;
		public static final int VROverlayInputMethod_Mouse = 1;
	};
	/** enum values */
	public static interface VROverlayTransformType {
		public static final int VROverlayTransformType_VROverlayTransform_Absolute = 0;
		public static final int VROverlayTransformType_VROverlayTransform_TrackedDeviceRelative = 1;
		public static final int VROverlayTransformType_VROverlayTransform_SystemOverlay = 2;
		public static final int VROverlayTransformType_VROverlayTransform_TrackedComponent = 3;
	};
	/** enum values */
	public static interface VROverlayFlags {
		public static final int VROverlayFlags_None = 0;
		public static final int VROverlayFlags_Curved = 1;
		public static final int VROverlayFlags_RGSS4X = 2;
		public static final int VROverlayFlags_NoDashboardTab = 3;
		public static final int VROverlayFlags_AcceptsGamepadEvents = 4;
		public static final int VROverlayFlags_ShowGamepadFocus = 5;
		public static final int VROverlayFlags_SendVRScrollEvents = 6;
		public static final int VROverlayFlags_SendVRTouchpadEvents = 7;
		public static final int VROverlayFlags_ShowTouchPadScrollWheel = 8;
		public static final int VROverlayFlags_TransferOwnershipToInternalProcess = 9;
		public static final int VROverlayFlags_SideBySide_Parallel = 10;
		public static final int VROverlayFlags_SideBySide_Crossed = 11;
		public static final int VROverlayFlags_Panorama = 12;
		public static final int VROverlayFlags_StereoPanorama = 13;
		public static final int VROverlayFlags_SortWithNonSceneOverlays = 14;
	};
	/** enum values */
	public static interface EGamepadTextInputMode {
		public static final int EGamepadTextInputMode_k_EGamepadTextInputModeNormal = 0;
		public static final int EGamepadTextInputMode_k_EGamepadTextInputModePassword = 1;
		public static final int EGamepadTextInputMode_k_EGamepadTextInputModeSubmit = 2;
	};
	/** enum values */
	public static interface EGamepadTextInputLineMode {
		public static final int EGamepadTextInputLineMode_k_EGamepadTextInputLineModeSingleLine = 0;
		public static final int EGamepadTextInputLineMode_k_EGamepadTextInputLineModeMultipleLines = 1;
	};
	/** enum values */
	public static interface EOverlayDirection {
		public static final int EOverlayDirection_OverlayDirection_Up = 0;
		public static final int EOverlayDirection_OverlayDirection_Down = 1;
		public static final int EOverlayDirection_OverlayDirection_Left = 2;
		public static final int EOverlayDirection_OverlayDirection_Right = 3;
		public static final int EOverlayDirection_OverlayDirection_Count = 4;
	};
	/** enum values */
	public static interface EVRRenderModelError {
		public static final int EVRRenderModelError_VRRenderModelError_None = 0;
		public static final int EVRRenderModelError_VRRenderModelError_Loading = 100;
		public static final int EVRRenderModelError_VRRenderModelError_NotSupported = 200;
		public static final int EVRRenderModelError_VRRenderModelError_InvalidArg = 300;
		public static final int EVRRenderModelError_VRRenderModelError_InvalidModel = 301;
		public static final int EVRRenderModelError_VRRenderModelError_NoShapes = 302;
		public static final int EVRRenderModelError_VRRenderModelError_MultipleShapes = 303;
		public static final int EVRRenderModelError_VRRenderModelError_TooManyVertices = 304;
		public static final int EVRRenderModelError_VRRenderModelError_MultipleTextures = 305;
		public static final int EVRRenderModelError_VRRenderModelError_BufferTooSmall = 306;
		public static final int EVRRenderModelError_VRRenderModelError_NotEnoughNormals = 307;
		public static final int EVRRenderModelError_VRRenderModelError_NotEnoughTexCoords = 308;
		public static final int EVRRenderModelError_VRRenderModelError_InvalidTexture = 400;
	};
	/** enum values */
	public static interface EVRComponentProperty {
		public static final int EVRComponentProperty_VRComponentProperty_IsStatic = 1;
		public static final int EVRComponentProperty_VRComponentProperty_IsVisible = 2;
		public static final int EVRComponentProperty_VRComponentProperty_IsTouched = 4;
		public static final int EVRComponentProperty_VRComponentProperty_IsPressed = 8;
		public static final int EVRComponentProperty_VRComponentProperty_IsScrolled = 16;
	};
	/** enum values */
	public static interface EVRNotificationType {
		public static final int EVRNotificationType_Transient = 0;
		public static final int EVRNotificationType_Persistent = 1;
		public static final int EVRNotificationType_Transient_SystemWithUserValue = 2;
	};
	/** enum values */
	public static interface EVRNotificationStyle {
		public static final int EVRNotificationStyle_None = 0;
		public static final int EVRNotificationStyle_Application = 100;
		public static final int EVRNotificationStyle_Contact_Disabled = 200;
		public static final int EVRNotificationStyle_Contact_Enabled = 201;
		public static final int EVRNotificationStyle_Contact_Active = 202;
	};
	/** enum values */
	public static interface EVRSettingsError {
		public static final int EVRSettingsError_VRSettingsError_None = 0;
		public static final int EVRSettingsError_VRSettingsError_IPCFailed = 1;
		public static final int EVRSettingsError_VRSettingsError_WriteFailed = 2;
		public static final int EVRSettingsError_VRSettingsError_ReadFailed = 3;
	};
	/** enum values */
	public static interface EVRScreenshotError {
		public static final int EVRScreenshotError_VRScreenshotError_None = 0;
		public static final int EVRScreenshotError_VRScreenshotError_RequestFailed = 1;
		public static final int EVRScreenshotError_VRScreenshotError_IncompatibleVersion = 100;
		public static final int EVRScreenshotError_VRScreenshotError_NotFound = 101;
		public static final int EVRScreenshotError_VRScreenshotError_BufferTooSmall = 102;
		public static final int EVRScreenshotError_VRScreenshotError_ScreenshotAlreadyInProgress = 108;
	};
	/** OpenVR Constants */
	public static final int k_unTrackingStringSize = 32;
	public static final int k_unMaxDriverDebugResponseSize = 32768;
	public static final int k_unTrackedDeviceIndex_Hmd = 0;
	public static final int k_unMaxTrackedDeviceCount = 16;
	public static final int k_unTrackedDeviceIndexOther = 0xFFFFFFFF;
	public static final int k_unTrackedDeviceIndexInvalid = 0xFFFFFFFF;
	public static final int k_unMaxPropertyStringSize = 32768;
	public static final int k_unControllerStateAxisCount = 5;
	public static final long k_ulOverlayHandleInvalid = 0;
	public static final int k_unScreenshotHandleInvalid = 0;
	public static final int k_unMaxApplicationKeyLength = 128;
	public static final int k_unVROverlayMaxKeyLength = 128;
	public static final int k_unVROverlayMaxNameLength = 128;
	public static final int k_unMaxOverlayCount = 32;
	public static final int k_unNotificationTextMaxSize = 256;
	public static final int k_unMaxSettingsKeyLength = 128;
	/**
	 * Global entry points<br>
	 * Original signature : <code>intptr_t VR_InitInternal(EVRInitError*, EVRApplicationType)</code><br>
	 * @deprecated use the safer methods {@link #VR_InitInternal(java.nio.IntBuffer, int)} and {@link #VR_InitInternal(com.sun.jna.ptr.IntByReference, int)} instead
	 */
	@Deprecated 
	public static native Pointer VR_InitInternal(IntByReference peError, int eType);
	/**
	 * Global entry points<br>
	 * Original signature : <code>intptr_t VR_InitInternal(EVRInitError*, EVRApplicationType)</code>
	 */
	public static native Pointer VR_InitInternal(IntBuffer peError, int eType);
	/** Original signature : <code>void VR_ShutdownInternal()</code> */
	public static native void VR_ShutdownInternal();
	/** Original signature : <code>bool VR_IsHmdPresent()</code> */
	public static native byte VR_IsHmdPresent();
	/**
	 * Original signature : <code>intptr_t VR_GetGenericInterface(const char*, EVRInitError*)</code><br>
	 * @deprecated use the safer methods {@link #VR_GetGenericInterface(java.lang.String, java.nio.IntBuffer)} and {@link #VR_GetGenericInterface(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	public static native Pointer VR_GetGenericInterface(Pointer pchInterfaceVersion, IntByReference peError);
	/** Original signature : <code>intptr_t VR_GetGenericInterface(const char*, EVRInitError*)</code> */
	public static native Pointer VR_GetGenericInterface(String pchInterfaceVersion, IntBuffer peError);
	/** Original signature : <code>bool VR_IsRuntimeInstalled()</code> */
	public static native byte VR_IsRuntimeInstalled();
	/** Original signature : <code>char* VR_GetVRInitErrorAsSymbol(EVRInitError)</code> */
	public static native Pointer VR_GetVRInitErrorAsSymbol(int error);
	/** Original signature : <code>char* VR_GetVRInitErrorAsEnglishDescription(EVRInitError)</code> */
	public static native Pointer VR_GetVRInitErrorAsEnglishDescription(int error);

	public static String IVRSystem_Version = "FnTable:IVRSystem_012";
	public static String IVRApplications_Version = "FnTable:IVRApplications_006";
	public static String IVRSettings_Version = "FnTable:IVRSettings_001";
	public static String IVRExtendedDisplay_Version = "FnTable:IVRExtendedDisplay_001";
	public static String IVRChaperone_Version = "FnTable:IVRChaperone_003";
	public static String IVRChaperoneSetup_Version = "FnTable:IVRChaperoneSetup_005";
	public static String IVRCompositor_Version = "FnTable:IVRCompositor_016";
	public static String IVROverlay_Version = "FnTable:IVROverlay_013";
	public static String IVRRenderModels_Version = "FnTable:IVRRenderModels_005";
	public static String IVRControlPanel_Version = "FnTable:IVRControlPanel_001";
	public static String IVRNotifications_Version = "FnTable:IVRNotifications_002";
	public static String IVRTrackedCamera_Version = "FnTable:IVRTrackedCamera_003";
        public static String IVRScreenshots_Version = "FnTable:IVRScreenshots_001";
        public static String IVRResources_Version = "FnTable:IVRResources_001";
}
