package com.jme3.system.jopenvr;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * An event posted by the server to all running applications<br>
 * <i>native declaration : headers\openvr_capi.h:1286</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class VREvent_t extends Structure {
	/** EVREventType enum */
	public int eventType;
	/** C type : TrackedDeviceIndex_t */
	public int trackedDeviceIndex;
	public float eventAgeSeconds;
	/** C type : VREvent_Data_t */
	public VREvent_Data_t data;
	public VREvent_t() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("eventType", "trackedDeviceIndex", "eventAgeSeconds", "data");
	}
	/**
	 * @param eventType EVREventType enum<br>
	 * @param trackedDeviceIndex C type : TrackedDeviceIndex_t<br>
	 * @param data C type : VREvent_Data_t
	 */
	public VREvent_t(int eventType, int trackedDeviceIndex, float eventAgeSeconds, VREvent_Data_t data) {
		super();
		this.eventType = eventType;
		this.trackedDeviceIndex = trackedDeviceIndex;
		this.eventAgeSeconds = eventAgeSeconds;
		this.data = data;
	}
	public VREvent_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends VREvent_t implements Structure.ByReference {
		
	};
	public static class ByValue extends VREvent_t implements Structure.ByValue {
		
	};
}
