package com.jme3.system.jopenvr;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : headers\openvr_capi.h:1395</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class VREvent_DualAnalog_t extends Structure {
	public float x;
	public float y;
	public float transformedX;
	public float transformedY;
	/**
	 * C type : EDualAnalogWhich
	 */
	public int which;
	public VREvent_DualAnalog_t() {
		super();
	}
        @Override
	protected List<String> getFieldOrder() {
		return Arrays.asList("x", "y", "transformedX", "transformedY", "which");
	}
	/**
	 * @param which @see JOpenVRLibrary.EDualAnalogWhich <br>
	 * C type : EDualAnalogWhich
	 */
	public VREvent_DualAnalog_t(float x, float y, float transformedX, float transformedY, int which) {
		super();
		this.x = x;
		this.y = y;
		this.transformedX = transformedX;
		this.transformedY = transformedY;
		this.which = which;
	}
	public VREvent_DualAnalog_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends VREvent_DualAnalog_t implements Structure.ByReference {
		
	};
	public static class ByValue extends VREvent_DualAnalog_t implements Structure.ByValue {
		
	};
}
