package com.jme3.system.jopenvr;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.IntByReference;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : headers\openvr_capi.h:1592</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CVRSettingHelper extends Structure {
	/**
	 * class vr::IVRSettings *<br>
	 * C type : intptr_t
	 */
	public IntByReference m_pSettings;
	public CVRSettingHelper() {
		super();
	}
        @Override
	protected List<String> getFieldOrder() {
		return Arrays.asList("m_pSettings");
	}
	/**
	 * @param m_pSettings class vr::IVRSettings *<br>
	 * C type : intptr_t
	 */
	public CVRSettingHelper(IntByReference m_pSettings) {
		super();
		this.m_pSettings = m_pSettings;
	}
	public CVRSettingHelper(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends CVRSettingHelper implements Structure.ByReference {
		
	};
	public static class ByValue extends CVRSettingHelper implements Structure.ByValue {
		
	};
}
