package com.jme3.system.jopenvr;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : headers\openvr_capi.h:1615</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class InputPoseActionData_t extends Structure {
	public byte bActive;
	/** C type : VRInputValueHandle_t */
	public long activeOrigin;
	/** C type : TrackedDevicePose_t */
	public TrackedDevicePose_t pose;
	public InputPoseActionData_t() {
		super();
	}
        @Override
	protected List<String> getFieldOrder() {
		return Arrays.asList("bActive", "activeOrigin", "pose");
	}
	/**
	 * @param activeOrigin C type : VRInputValueHandle_t<br>
	 * @param pose C type : TrackedDevicePose_t
	 */
	public InputPoseActionData_t(byte bActive, long activeOrigin, TrackedDevicePose_t pose) {
		super();
		this.bActive = bActive;
		this.activeOrigin = activeOrigin;
		this.pose = pose;
	}
	public InputPoseActionData_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends InputPoseActionData_t implements Structure.ByReference {
		
	};
	public static class ByValue extends InputPoseActionData_t implements Structure.ByValue {
		
	};
}
