/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_audio_ios_IosEFX */

#ifndef _Included_com_jme3_audio_ios_IosEFX
#define _Included_com_jme3_audio_ios_IosEFX
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_audio_ios_IosEFX
 * Method:    alGenAuxiliaryEffectSlots
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_audio_ios_IosEFX_alGenAuxiliaryEffectSlots
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_jme3_audio_ios_IosEFX
 * Method:    alGenEffects
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_audio_ios_IosEFX_alGenEffects
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_jme3_audio_ios_IosEFX
 * Method:    alEffecti
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_jme3_audio_ios_IosEFX_alEffecti
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_jme3_audio_ios_IosEFX
 * Method:    alAuxiliaryEffectSloti
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_jme3_audio_ios_IosEFX_alAuxiliaryEffectSloti
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_jme3_audio_ios_IosEFX
 * Method:    alDeleteEffects
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_audio_ios_IosEFX_alDeleteEffects
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_jme3_audio_ios_IosEFX
 * Method:    alDeleteAuxiliaryEffectSlots
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_audio_ios_IosEFX_alDeleteAuxiliaryEffectSlots
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_jme3_audio_ios_IosEFX
 * Method:    alGenFilters
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_audio_ios_IosEFX_alGenFilters
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_jme3_audio_ios_IosEFX
 * Method:    alFilteri
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_jme3_audio_ios_IosEFX_alFilteri
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_jme3_audio_ios_IosEFX
 * Method:    alFilterf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_audio_ios_IosEFX_alFilterf
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     com_jme3_audio_ios_IosEFX
 * Method:    alDeleteFilters
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_audio_ios_IosEFX_alDeleteFilters
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_jme3_audio_ios_IosEFX
 * Method:    alEffectf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_audio_ios_IosEFX_alEffectf
  (JNIEnv *, jobject, jint, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
