frame.title=Display Settings for {0}

button.ok=Continue
button.cancel=Cancel

checkbox.fullscreen=Fullscreen?
checkbox.vsync=Vsync?
checkbox.gamma=Gamma correction
checkbox.x11PlatformPreferred=Prefer X11

label.resolutions=Resolution
label.colordepth=Color Depth
label.refresh=Refresh Rate
label.antialias=Anti-Aliasing
label.renderer=Renderer
label.displayScaleMode=Display Scale

displayScaleMode.disabled=Disabled
displayScaleMode.nativePixels=Native pixels
displayScaleMode.dpiAware=DPI aware
displayScaleMode.supersampling=Supersampling {0}x

antialias.disabled=Disabled
refresh.na=n/a

error.unsupportedmode=Your monitor reports that it does not support the display mode you\'ve selected.\nThe combination of bit depth and refresh rate is not supported.
