package com.jme3.system.osvr.osvrclientreporttypes;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class OSVR_PositionReport extends Structure {
	public int sensor;
	/** C type : OSVR_PositionState */
	public OSVR_Vec3 xyz;
	public OSVR_PositionReport() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("sensor", "xyz");
	}
	/** @param xyz C type : OSVR_PositionState */
	public OSVR_PositionReport(int sensor, OSVR_Vec3 xyz) {
		super();
		this.sensor = sensor;
		this.xyz = xyz;
	}
	public OSVR_PositionReport(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends OSVR_PositionReport implements Structure.ByReference {
		
	};
	public static class ByValue extends OSVR_PositionReport implements Structure.ByValue {
		
	};
}
