/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_collision_shapes_HeightfieldCollisionShape */

#ifndef _Included_com_jme3_bullet_collision_shapes_HeightfieldCollisionShape
#define _Included_com_jme3_bullet_collision_shapes_HeightfieldCollisionShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_collision_shapes_HeightfieldCollisionShape
 * Method:    createShape
 * Signature: (IILjava/nio/ByteBuffer;FFFIZ)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_collision_shapes_HeightfieldCollisionShape_createShape
  (JNIEnv *, jobject, jint, jint, jobject, jfloat, jfloat, jfloat, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
