/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_collision_shapes_CapsuleCollisionShape */

#ifndef _Included_com_jme3_bullet_collision_shapes_CapsuleCollisionShape
#define _Included_com_jme3_bullet_collision_shapes_CapsuleCollisionShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_collision_shapes_CapsuleCollisionShape
 * Method:    createShape
 * Signature: (IFF)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_collision_shapes_CapsuleCollisionShape_createShape
  (JNIEnv *, jobject, jint, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
