/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_util_NativeMeshUtil */

#ifndef _Included_com_jme3_bullet_util_NativeMeshUtil
#define _Included_com_jme3_bullet_util_NativeMeshUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_util_NativeMeshUtil
 * Method:    createTriangleIndexVertexArray
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_util_NativeMeshUtil_createTriangleIndexVertexArray
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
