/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_collision_shapes_CylinderCollisionShape */

#ifndef _Included_com_jme3_bullet_collision_shapes_CylinderCollisionShape
#define _Included_com_jme3_bullet_collision_shapes_CylinderCollisionShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_collision_shapes_CylinderCollisionShape
 * Method:    createShape
 * Signature: (ILcom/jme3/math/Vector3f;)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_collision_shapes_CylinderCollisionShape_createShape
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
