name: "VulkanTest"
# Links type placeholders to full class names used for instantiation
# by reflection. This enables custom types to be used. Common engine
# types are supported by default.
imports:
  MyUniformType: "com.username.MyCustomUniform"
  MyBufferMember: "com.username.MyCustomBufferMember"
  MyRasterState: "com.username.MyCustomRasterState"
parameters:
  # Most valid parameter arguments are defined by managing Uniform object
  # including default values. Exceptions are type, set, and define.
  # Also, binding and stages are handled by AbstractUniform.
  Matrices:
    type: UniformBuffer
    layout: # defines the layout of the uniform buffer
      worldViewProjection:
        type: Matrix4f
      time:
        type: Float
        default: 1.0
      myval:
        type: com.username.hello.world.MyBufferMember
        default: "parse_this"
  BaseColorMap:
    type: Texture
    default: "Common/Textures/MissingTexture.jpg"
  MyValue:
    type: MyUniformType
    default: "parse_this"
pipelines:
  main:
    type: GraphicsState
    shaders:
      - stage: Vertex
        file: "Shaders/VulkanVertTest.yml"
        entry: "main"
      - stage: Fragment
        file: "Shaders/VulkanFragTest.yml"
        # entry is "main" by default
    layout:
      - name: "Matrices"
        descriptor: UniformBuffer
        stages: [Vertex]
        set: 0
        binding: 0
      - name: "BaseColorMap"
        descriptor: CombinedImageSampler
        stages: [Fragment]
        set: 0
        binding: 1
    renderHints:
      cullMode: None
      blendAttachments:
        - colorWriteMask: [R, G, B, A]
          blend: false
          srcColorFactor: One
          dstColorFactor: Zero
          colorOp: Add
          srcAlphaFactor: One
          dstAlphaFactor: Zero
          alphaOp: Add

