name: "VulkanTest"
# Links type placeholders to full class names used for instantiation
# by reflection. This enables custom types to be used. Common engine
# types are supported by default.
imports:
  MyUniformType: "com.username.MyCustomUniform"
  MyBufferMember: "com.username.MyCustomBufferMember"
  MyRasterState: "com.username.MyCustomRasterState"
parameters:
  # Most valid parameter arguments are defined by managing Uniform object
  # including default values. Exceptions are type, set, and define.
  # Also, binding and stages are handled by AbstractUniform.
  Matrices:
    type: UniformBuffer
    set: 0
    binding: 0
    usage: Stream
    stages: [Vertex]
    layout: # defines the layout of the uniform buffer
      worldViewProjection:
        type: Matrix4f
      time:
        type: Float
        default: 1.0
      myval:
        type: MyBufferMember
        default: "parse_this"
  BaseColorMap:
    type: Texture
    set: 0
    binding: 1
    define: "BASE_COLOR_MAP"
    default: "Common/Textures/MissingTexture.jpg"
  MyValue:
    type: MyUniformType
    set: 0
    binding: 1
    default: "parse_this"
pipelines:
  main:
    type: GraphicsPipeline
    shaders:
      - stage: Vertex
        file: "Shaders/VulkanVertTest.yml"
        entry: "main"
      - stage: Fragment
        file: "Shaders/VulkanFragTest.yml"
        # entry is "main" by default
    dynamic: [ViewPort, Scissor]
    raster:
      type: MyRasterState
      cullMode: None
    colorBlend:
      attachments:
        - colorWriteMask: [R, G, B, A]
          blend: false
          srcColorFactor: One
          dstColorFactor: Zero
          colorOp: Add
          srcAlphaFactor: One
          dstAlphaFactor: Zero
          alphaOp: Add
    viewPort:
      viewPorts:
        - x: 0
          y: 0
          w: 128
          h: 128
      scissors:
        - x: 0.0
          y: 0.0
          w: 1.0
          h: 1.0

