/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jme3.gde.gui;

import com.jme3.gde.gui.nodes.GElementNode;
import com.jme3.gde.gui.nodes.ScreenChildFactory;
import jada.ngeditor.controller.GUIEditor;
import jada.ngeditor.model.elements.GElement;
import java.awt.BorderLayout;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JComponent;
import org.netbeans.spi.navigator.NavigatorPanel;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.BeanTreeView;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.nodes.Node;
import org.openide.util.Exceptions;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.util.Utilities;
import org.openide.util.lookup.ProxyLookup;
import org.openide.windows.TopComponent;

/**
 *
 * @author cris
 */
@NavigatorPanel.Registration(mimeType = "text/x-niftygui+xml", displayName="Gui View")
public class Navigator extends javax.swing.JPanel implements NavigatorPanel,ExplorerManager.Provider , Observer, PropertyChangeListener, LookupListener{
    private Lookup lookup;
    private  ExplorerManager mgr = new ExplorerManager();
    private final BeanTreeView beanTreeView;
    private GUIEditor editor;
    private Lookup context;
    private boolean lock;
    /**
     * Creates new form Navigator
     */
    public Navigator() {
        initComponents();
        setLayout(new BorderLayout());
        beanTreeView = new BeanTreeView();
        add(beanTreeView, BorderLayout.CENTER);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public String getDisplayName() {
       return "GuiView";
    }

    @Override
    public String getDisplayHint() {
       return "Easy view for your gui";
    }

    @Override
    public JComponent getComponent() {
       return this;
    }

    @Override
    public void panelActivated(Lookup context) {
        try {
            this.context = context;
            context.lookupResult(NiftyGuiDataObject.class).addLookupListener(this);
            intNavigator(context);
        } catch (PropertyVetoException ex) {
            Exceptions.printStackTrace(ex);
        }
    }

    @Override
    public void panelDeactivated() {
        ExplorerUtils.activateActions(mgr, false);
    }

    @Override
    public Lookup getLookup() {
       return lookup;
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return mgr;
    }

    @Override
    public void update(Observable o, Object arg) {
        
        jada.ngeditor.listeners.actions.Action act = ( jada.ngeditor.listeners.actions.Action) arg;
       if(act.getType() == jada.ngeditor.listeners.actions.Action.SEL){
           ArrayList<String> path = new ArrayList<String>();
           GElement parent = act.getGUIElement();
           while(parent!=null){
               path.add(parent.getID());
               parent = parent.getParent();
           }
           Node result = mgr.getRootContext();
           for(int i=path.size()-1;i>=0;i--){
               result = result.getChildren().findChild(path.get(i));
           }
            try {
                mgr.setSelectedNodes(new Node[]{result});
            } catch (PropertyVetoException ex) {
                Exceptions.printStackTrace(ex);
            }
       }else  if(act.getType() == jada.ngeditor.listeners.actions.Action.NEW){
            try {
                this.intNavigator(context);
            } catch (PropertyVetoException ex) {
                Exceptions.printStackTrace(ex);
            }
       }
        beanTreeView.updateUI();
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals(ExplorerManager.PROP_SELECTED_NODES)) {
            Node[] newValue = (Node[]) evt.getNewValue();
            if (newValue.length > 0) {
                AbstractNode firstSelected = (AbstractNode) newValue[0];
                if (firstSelected instanceof GElementNode) {
                    GElement element = ((GElementNode) firstSelected).getGelement();
                    
                    editor.selectElement(element);
                    
                }
            }
        }
    }

    @Override
    public void resultChanged(LookupEvent ev) {
        try {
            intNavigator(context);
        } catch (PropertyVetoException ex) {
            Exceptions.printStackTrace(ex);
        }
    }

    private void intNavigator(Lookup context) throws PropertyVetoException {
        
        NiftyGuiDataObject man = context.lookup(NiftyGuiDataObject.class);
        ExplorerUtils.activateActions(mgr, true);
        editor = man.getLookup().lookup(GUIEditor.class);
        AbstractNode guiRoot = new AbstractNode(Children.create(new ScreenChildFactory(editor.getGui()), true));
        guiRoot.setName("Gui");
        this.mgr.setRootContext(guiRoot);
        this.beanTreeView.updateUI();
        mgr.addPropertyChangeListener(this);
        this.mgr.setSelectedNodes(new Node[]{guiRoot});
        Lookup lookup1 = ExplorerUtils.createLookup(mgr, getActionMap());
        lookup = new ProxyLookup(lookup1);
        editor.addObserver(this);
    }
}
