package com.jme3.system.osvr.osvrrendermanager;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class OSVR_RGB extends Structure {
	public float r;
	public float g;
	public float b;
	public OSVR_RGB() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("r", "g", "b");
	}
	public OSVR_RGB(float r, float g, float b) {
		super();
		this.r = r;
		this.g = g;
		this.b = b;
	}
	public OSVR_RGB(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends OSVR_RGB implements Structure.ByReference {
		
	};
	public static class ByValue extends OSVR_RGB implements Structure.ByValue {
		
	};
}
