/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_util_DebugShapeFactory */

#ifndef _Included_com_jme3_bullet_util_DebugShapeFactory
#define _Included_com_jme3_bullet_util_DebugShapeFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_util_DebugShapeFactory
 * Method:    getVertices
 * Signature: (JLcom/jme3/bullet/util/DebugMeshCallback;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_util_DebugShapeFactory_getVertices
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
