/*
 * Copyright (c) 2009-2026 jMonkeyEngine
 * All rights reserved.
 */
package com.jme3.input.ios;

import static com.jme3.input.KeyInput.KEY_0;
import static com.jme3.input.KeyInput.KEY_1;
import static com.jme3.input.KeyInput.KEY_2;
import static com.jme3.input.KeyInput.KEY_3;
import static com.jme3.input.KeyInput.KEY_4;
import static com.jme3.input.KeyInput.KEY_5;
import static com.jme3.input.KeyInput.KEY_6;
import static com.jme3.input.KeyInput.KEY_7;
import static com.jme3.input.KeyInput.KEY_8;
import static com.jme3.input.KeyInput.KEY_9;
import static com.jme3.input.KeyInput.KEY_A;
import static com.jme3.input.KeyInput.KEY_ADD;
import static com.jme3.input.KeyInput.KEY_APOSTROPHE;
import static com.jme3.input.KeyInput.KEY_B;
import static com.jme3.input.KeyInput.KEY_BACK;
import static com.jme3.input.KeyInput.KEY_BACKSLASH;
import static com.jme3.input.KeyInput.KEY_C;
import static com.jme3.input.KeyInput.KEY_CAPITAL;
import static com.jme3.input.KeyInput.KEY_COMMA;
import static com.jme3.input.KeyInput.KEY_D;
import static com.jme3.input.KeyInput.KEY_DECIMAL;
import static com.jme3.input.KeyInput.KEY_DELETE;
import static com.jme3.input.KeyInput.KEY_DIVIDE;
import static com.jme3.input.KeyInput.KEY_DOWN;
import static com.jme3.input.KeyInput.KEY_E;
import static com.jme3.input.KeyInput.KEY_END;
import static com.jme3.input.KeyInput.KEY_EQUALS;
import static com.jme3.input.KeyInput.KEY_ESCAPE;
import static com.jme3.input.KeyInput.KEY_F;
import static com.jme3.input.KeyInput.KEY_F1;
import static com.jme3.input.KeyInput.KEY_F10;
import static com.jme3.input.KeyInput.KEY_F11;
import static com.jme3.input.KeyInput.KEY_F12;
import static com.jme3.input.KeyInput.KEY_F13;
import static com.jme3.input.KeyInput.KEY_F14;
import static com.jme3.input.KeyInput.KEY_F15;
import static com.jme3.input.KeyInput.KEY_F2;
import static com.jme3.input.KeyInput.KEY_F3;
import static com.jme3.input.KeyInput.KEY_F4;
import static com.jme3.input.KeyInput.KEY_F5;
import static com.jme3.input.KeyInput.KEY_F6;
import static com.jme3.input.KeyInput.KEY_F7;
import static com.jme3.input.KeyInput.KEY_F8;
import static com.jme3.input.KeyInput.KEY_F9;
import static com.jme3.input.KeyInput.KEY_G;
import static com.jme3.input.KeyInput.KEY_GRAVE;
import static com.jme3.input.KeyInput.KEY_H;
import static com.jme3.input.KeyInput.KEY_HOME;
import static com.jme3.input.KeyInput.KEY_I;
import static com.jme3.input.KeyInput.KEY_INSERT;
import static com.jme3.input.KeyInput.KEY_J;
import static com.jme3.input.KeyInput.KEY_K;
import static com.jme3.input.KeyInput.KEY_L;
import static com.jme3.input.KeyInput.KEY_LBRACKET;
import static com.jme3.input.KeyInput.KEY_LCONTROL;
import static com.jme3.input.KeyInput.KEY_LEFT;
import static com.jme3.input.KeyInput.KEY_LMENU;
import static com.jme3.input.KeyInput.KEY_LMETA;
import static com.jme3.input.KeyInput.KEY_LSHIFT;
import static com.jme3.input.KeyInput.KEY_M;
import static com.jme3.input.KeyInput.KEY_MINUS;
import static com.jme3.input.KeyInput.KEY_MULTIPLY;
import static com.jme3.input.KeyInput.KEY_N;
import static com.jme3.input.KeyInput.KEY_NEXT;
import static com.jme3.input.KeyInput.KEY_NUMLOCK;
import static com.jme3.input.KeyInput.KEY_NUMPAD0;
import static com.jme3.input.KeyInput.KEY_NUMPAD1;
import static com.jme3.input.KeyInput.KEY_NUMPAD2;
import static com.jme3.input.KeyInput.KEY_NUMPAD3;
import static com.jme3.input.KeyInput.KEY_NUMPAD4;
import static com.jme3.input.KeyInput.KEY_NUMPAD5;
import static com.jme3.input.KeyInput.KEY_NUMPAD6;
import static com.jme3.input.KeyInput.KEY_NUMPAD7;
import static com.jme3.input.KeyInput.KEY_NUMPAD8;
import static com.jme3.input.KeyInput.KEY_NUMPAD9;
import static com.jme3.input.KeyInput.KEY_NUMPADENTER;
import static com.jme3.input.KeyInput.KEY_O;
import static com.jme3.input.KeyInput.KEY_P;
import static com.jme3.input.KeyInput.KEY_PAUSE;
import static com.jme3.input.KeyInput.KEY_PERIOD;
import static com.jme3.input.KeyInput.KEY_PRIOR;
import static com.jme3.input.KeyInput.KEY_Q;
import static com.jme3.input.KeyInput.KEY_R;
import static com.jme3.input.KeyInput.KEY_RBRACKET;
import static com.jme3.input.KeyInput.KEY_RCONTROL;
import static com.jme3.input.KeyInput.KEY_RETURN;
import static com.jme3.input.KeyInput.KEY_RIGHT;
import static com.jme3.input.KeyInput.KEY_RMENU;
import static com.jme3.input.KeyInput.KEY_RMETA;
import static com.jme3.input.KeyInput.KEY_RSHIFT;
import static com.jme3.input.KeyInput.KEY_S;
import static com.jme3.input.KeyInput.KEY_SCROLL;
import static com.jme3.input.KeyInput.KEY_SEMICOLON;
import static com.jme3.input.KeyInput.KEY_SLASH;
import static com.jme3.input.KeyInput.KEY_SPACE;
import static com.jme3.input.KeyInput.KEY_SUBTRACT;
import static com.jme3.input.KeyInput.KEY_SYSRQ;
import static com.jme3.input.KeyInput.KEY_T;
import static com.jme3.input.KeyInput.KEY_TAB;
import static com.jme3.input.KeyInput.KEY_U;
import static com.jme3.input.KeyInput.KEY_UNKNOWN;
import static com.jme3.input.KeyInput.KEY_UP;
import static com.jme3.input.KeyInput.KEY_V;
import static com.jme3.input.KeyInput.KEY_W;
import static com.jme3.input.KeyInput.KEY_X;
import static com.jme3.input.KeyInput.KEY_Y;
import static com.jme3.input.KeyInput.KEY_Z;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_0;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_1;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_2;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_3;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_4;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_5;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_6;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_7;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_8;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_9;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_A;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_APOSTROPHE;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_B;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_BACKSLASH;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_BACKSPACE;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_C;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_CAPSLOCK;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_COMMA;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_COUNT;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_D;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_DELETE;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_DOWN;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_E;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_END;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_EQUALS;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_ESCAPE;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_F;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_F1;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_F10;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_F11;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_F12;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_F13;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_F14;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_F15;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_F2;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_F3;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_F4;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_F5;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_F6;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_F7;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_F8;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_F9;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_G;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_GRAVE;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_H;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_HOME;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_I;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_INSERT;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_J;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_K;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_KP_0;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_KP_1;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_KP_2;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_KP_3;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_KP_4;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_KP_5;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_KP_6;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_KP_7;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_KP_8;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_KP_9;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_KP_DIVIDE;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_KP_ENTER;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_KP_MINUS;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_KP_MULTIPLY;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_KP_PERIOD;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_KP_PLUS;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_L;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_LALT;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_LCTRL;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_LEFT;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_LEFTBRACKET;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_LGUI;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_LSHIFT;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_M;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_MINUS;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_N;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_NUMLOCKCLEAR;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_O;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_P;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_PAGEDOWN;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_PAGEUP;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_PAUSE;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_PERIOD;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_PRINTSCREEN;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_Q;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_R;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_RALT;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_RCTRL;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_RETURN;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_RGUI;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_RIGHT;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_RIGHTBRACKET;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_RSHIFT;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_S;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_SCROLLLOCK;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_SEMICOLON;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_SLASH;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_SPACE;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_T;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_TAB;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_U;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_UP;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_V;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_W;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_X;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_Y;
import static org.ngengine.libjglios.sdl3.SDL3.SDL_SCANCODE_Z;

final class IosSdlKeyMap {
    private static final int[] SDL_TO_JME_KEY_MAP = new int[SDL_SCANCODE_COUNT];

    private IosSdlKeyMap() {
    }

    private static void reg(int jmeKey, int sdlScancode) {
        SDL_TO_JME_KEY_MAP[sdlScancode] = jmeKey;
    }

    static {
        reg(KEY_ESCAPE, SDL_SCANCODE_ESCAPE);
        reg(KEY_1, SDL_SCANCODE_1);
        reg(KEY_2, SDL_SCANCODE_2);
        reg(KEY_3, SDL_SCANCODE_3);
        reg(KEY_4, SDL_SCANCODE_4);
        reg(KEY_5, SDL_SCANCODE_5);
        reg(KEY_6, SDL_SCANCODE_6);
        reg(KEY_7, SDL_SCANCODE_7);
        reg(KEY_8, SDL_SCANCODE_8);
        reg(KEY_9, SDL_SCANCODE_9);
        reg(KEY_0, SDL_SCANCODE_0);
        reg(KEY_MINUS, SDL_SCANCODE_MINUS);
        reg(KEY_EQUALS, SDL_SCANCODE_EQUALS);
        reg(KEY_BACK, SDL_SCANCODE_BACKSPACE);
        reg(KEY_TAB, SDL_SCANCODE_TAB);
        reg(KEY_Q, SDL_SCANCODE_Q);
        reg(KEY_W, SDL_SCANCODE_W);
        reg(KEY_E, SDL_SCANCODE_E);
        reg(KEY_R, SDL_SCANCODE_R);
        reg(KEY_T, SDL_SCANCODE_T);
        reg(KEY_Y, SDL_SCANCODE_Y);
        reg(KEY_U, SDL_SCANCODE_U);
        reg(KEY_I, SDL_SCANCODE_I);
        reg(KEY_O, SDL_SCANCODE_O);
        reg(KEY_P, SDL_SCANCODE_P);
        reg(KEY_LBRACKET, SDL_SCANCODE_LEFTBRACKET);
        reg(KEY_RBRACKET, SDL_SCANCODE_RIGHTBRACKET);
        reg(KEY_RETURN, SDL_SCANCODE_RETURN);
        reg(KEY_LCONTROL, SDL_SCANCODE_LCTRL);
        reg(KEY_A, SDL_SCANCODE_A);
        reg(KEY_S, SDL_SCANCODE_S);
        reg(KEY_D, SDL_SCANCODE_D);
        reg(KEY_F, SDL_SCANCODE_F);
        reg(KEY_G, SDL_SCANCODE_G);
        reg(KEY_H, SDL_SCANCODE_H);
        reg(KEY_J, SDL_SCANCODE_J);
        reg(KEY_K, SDL_SCANCODE_K);
        reg(KEY_L, SDL_SCANCODE_L);
        reg(KEY_SEMICOLON, SDL_SCANCODE_SEMICOLON);
        reg(KEY_APOSTROPHE, SDL_SCANCODE_APOSTROPHE);
        reg(KEY_GRAVE, SDL_SCANCODE_GRAVE);
        reg(KEY_LSHIFT, SDL_SCANCODE_LSHIFT);
        reg(KEY_BACKSLASH, SDL_SCANCODE_BACKSLASH);
        reg(KEY_Z, SDL_SCANCODE_Z);
        reg(KEY_X, SDL_SCANCODE_X);
        reg(KEY_C, SDL_SCANCODE_C);
        reg(KEY_V, SDL_SCANCODE_V);
        reg(KEY_B, SDL_SCANCODE_B);
        reg(KEY_N, SDL_SCANCODE_N);
        reg(KEY_M, SDL_SCANCODE_M);
        reg(KEY_COMMA, SDL_SCANCODE_COMMA);
        reg(KEY_PERIOD, SDL_SCANCODE_PERIOD);
        reg(KEY_SLASH, SDL_SCANCODE_SLASH);
        reg(KEY_RSHIFT, SDL_SCANCODE_RSHIFT);
        reg(KEY_MULTIPLY, SDL_SCANCODE_KP_MULTIPLY);
        reg(KEY_LMENU, SDL_SCANCODE_LALT);
        reg(KEY_SPACE, SDL_SCANCODE_SPACE);
        reg(KEY_CAPITAL, SDL_SCANCODE_CAPSLOCK);
        reg(KEY_F1, SDL_SCANCODE_F1);
        reg(KEY_F2, SDL_SCANCODE_F2);
        reg(KEY_F3, SDL_SCANCODE_F3);
        reg(KEY_F4, SDL_SCANCODE_F4);
        reg(KEY_F5, SDL_SCANCODE_F5);
        reg(KEY_F6, SDL_SCANCODE_F6);
        reg(KEY_F7, SDL_SCANCODE_F7);
        reg(KEY_F8, SDL_SCANCODE_F8);
        reg(KEY_F9, SDL_SCANCODE_F9);
        reg(KEY_F10, SDL_SCANCODE_F10);
        reg(KEY_NUMLOCK, SDL_SCANCODE_NUMLOCKCLEAR);
        reg(KEY_SCROLL, SDL_SCANCODE_SCROLLLOCK);
        reg(KEY_NUMPAD7, SDL_SCANCODE_KP_7);
        reg(KEY_NUMPAD8, SDL_SCANCODE_KP_8);
        reg(KEY_NUMPAD9, SDL_SCANCODE_KP_9);
        reg(KEY_SUBTRACT, SDL_SCANCODE_KP_MINUS);
        reg(KEY_NUMPAD4, SDL_SCANCODE_KP_4);
        reg(KEY_NUMPAD5, SDL_SCANCODE_KP_5);
        reg(KEY_NUMPAD6, SDL_SCANCODE_KP_6);
        reg(KEY_ADD, SDL_SCANCODE_KP_PLUS);
        reg(KEY_NUMPAD1, SDL_SCANCODE_KP_1);
        reg(KEY_NUMPAD2, SDL_SCANCODE_KP_2);
        reg(KEY_NUMPAD3, SDL_SCANCODE_KP_3);
        reg(KEY_NUMPAD0, SDL_SCANCODE_KP_0);
        reg(KEY_DECIMAL, SDL_SCANCODE_KP_PERIOD);
        reg(KEY_F11, SDL_SCANCODE_F11);
        reg(KEY_F12, SDL_SCANCODE_F12);
        reg(KEY_F13, SDL_SCANCODE_F13);
        reg(KEY_F14, SDL_SCANCODE_F14);
        reg(KEY_F15, SDL_SCANCODE_F15);
        reg(KEY_NUMPADENTER, SDL_SCANCODE_KP_ENTER);
        reg(KEY_RCONTROL, SDL_SCANCODE_RCTRL);
        reg(KEY_DIVIDE, SDL_SCANCODE_KP_DIVIDE);
        reg(KEY_SYSRQ, SDL_SCANCODE_PRINTSCREEN);
        reg(KEY_RMENU, SDL_SCANCODE_RALT);
        reg(KEY_PAUSE, SDL_SCANCODE_PAUSE);
        reg(KEY_HOME, SDL_SCANCODE_HOME);
        reg(KEY_UP, SDL_SCANCODE_UP);
        reg(KEY_PRIOR, SDL_SCANCODE_PAGEUP);
        reg(KEY_LEFT, SDL_SCANCODE_LEFT);
        reg(KEY_RIGHT, SDL_SCANCODE_RIGHT);
        reg(KEY_END, SDL_SCANCODE_END);
        reg(KEY_DOWN, SDL_SCANCODE_DOWN);
        reg(KEY_NEXT, SDL_SCANCODE_PAGEDOWN);
        reg(KEY_INSERT, SDL_SCANCODE_INSERT);
        reg(KEY_DELETE, SDL_SCANCODE_DELETE);
        reg(KEY_LMETA, SDL_SCANCODE_LGUI);
        reg(KEY_RMETA, SDL_SCANCODE_RGUI);
    }

    static int toJmeKeyCode(int sdlScancode) {
        if (sdlScancode < 0 || sdlScancode >= SDL_TO_JME_KEY_MAP.length) {
            return KEY_UNKNOWN;
        }
        return SDL_TO_JME_KEY_MAP[sdlScancode];
    }
}
