name: Mesa Compliance Testing
on:
  - push
  - pull_request

jobs:
  MesaTests:
    name: Mesa Compliance Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: MeFisto94/jme3-testing
      - uses: actions/checkout@v2
        with:
          path: engine

      - name: setup-docker
        uses: docker-practice/actions-setup-docker@0.0.1
      - name: Fetch Docker Image
        run: sudo docker pull riccardoblb/buildenvs:javagl
      - name: Prebuild Everything # This task is so we don't get the whole compilation output verbosely in the test tasks.
        run: ./gradlew assemble

      - name: Test on LWJGL3
        run: |
          chmod +x ci-runner.sh
          NO_INTERRACTIVE=1 ./ci-runner.sh -Dmesa-llvm-ci=true tests-lwjgl3:test -i
      - name: Upload lwjgl3 reports
        uses: actions/upload-artifact@v1.0.0
        if: always()
        with:
          name: reports-lwjgl3
          path: tests-lwjgl3/build/reports

      - name: Test on LWJGL2
        if: always()
        run: |
          chmod +x ci-runner.sh
          NO_INTERRACTIVE=1 ./ci-runner.sh -Dmesa-llvm-ci=true tests-lwjgl2:test -i
      - name: Upload lwjgl2 reports
        uses: actions/upload-artifact@v1.0.0
        if: always()
        with:
          name: reports-lwjgl2
          path: tests-lwjgl2/build/reports
